
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  labels:
    app: myapp
spec:
  replicas: 5
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp-container
        image: containous/whoami
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  selector:
    app: myapp
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 80
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: myapp-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: myapp-service
          servicePort: 8000
#
# At this point you can connect to port 8000 on
# any ip address on the host and it should connect
# to a pod and give you whoami information.
#
# Run multiple times to see it switch which pod responds.
#
# and you can connect to port 80 on the k3s master
# and the ingress will get you to a working container
#
# on a 4-pi cluster of pi4 it takes about 3 secs to have
# a pod restart if you set replicas=1 and manually delete
# the only working pod (as a test)
#



