
###############################################################
#
# note the namespace mosquitto here
#
# uncertain if using a separate namespace here matters
# but it (likely) keeps containers etc. apart regardless
#
# minimal mosquitto broker example
# ref:  https://serverfault.com/questions/1045712/how-to-setup-mosquitto-mqtt-broker-in-kubernetes
#
###############################################################

---
apiVersion: v1
kind: Namespace
metadata:
  name: mosquitto

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquitto-config
  namespace: mosquitto
data:
  mosquitto.conf: |-

    allow_anonymous true
    listener 9001
    protocol websockets
    listener 1883
    protocol mqtt

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mosquitto
  namespace: mosquitto
spec:
  selector:
    matchLabels:
      app: mosquitto
  template:
    metadata:
      labels:
        app: mosquitto
    spec:
      containers:
      - name: mosquitto
        image: eclipse-mosquitto:2.0
        resources:
          requests:
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 1883
        volumeMounts:
            - name: mosquitto-config
              mountPath: /mosquitto/config/mosquitto.conf
              subPath: mosquitto.conf
      volumes:
        - name: mosquitto-config
          configMap:
            name: mosquitto-config

---

#
# use klipper loadbalancer
#   ref: https://kubernetes.io/docs/concepts/services-networking/service/#loadbalancer

# this only works for a one-node k3s cluster
# clusterIP doesn't appear to be needed for k3s
# ingress.ip is the ip of the k3s host

apiVersion: v1
kind: Service
metadata:
  name: mosquitto-lb
  namespace: mosquitto
spec:
  selector:
    app: mosquitto
  ports:
    - name: "1883"
      protocol: TCP
      port: 1883
      targetPort: 1883
    - name: "9001"
      protocol: TCP
      port: 9001
      targetPort: 9001
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 192.168.1.232

